---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    dnf: 
      update_cache: yes

  - name: install apache2 package
    dnf:
      name: httpd
      state: absent

  - name: add php support for apache
    dnf: 
      name: php
      state: absent

  - name: addl php support, php-pear for php package support
    dnf:
      name: php-pear
      state: absent

  - name: addl php support, php-mysqlnd for mysql
    dnf:
      name: php-mysqlnd
      state: absent
